version: "3.8"
services:
  # Proxies requests to internal services
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # network_mode: host
  datauno-app:
    image: nishantpanwar77/antimatterui:latest
    container_name: datauno-app
    restart: always
    ports:
      - 3000:3000
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: tabix
    restart: always
    links:
      - clickhouse
    ports:
      - 8181:80
    # VALUES:
    # NAME: CH
    # UserName: default
